using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OnlineVotingS.Domain.Errors
{
    public enum ErrorCodes
    {
        ELECTION_NOT_FOUND,
        ELECTION_CREATION_FAILED,
        ELECTION_DELETION_FAILED,
        ELECTION_UPDATE_FAILED,
        ELECTION_ALREADY_COMPLETED,
        ELECTION_NOT_ACTIVE,
        ELECTION_TITLE_MISSING,
        CAMPAIGN_NOT_FOUND,
        CAMPAIGN_CREATION_FAILED,
        CAMPAIGN_DELETION_FAILED,
        CAMPAIGN_UPDATE_FAILED,
        CANDIDATE_CREATION_FAILED,
        CANDIDATE_DELETION_FAILED,
        CANDIDATE_UPDATE_FAILED,
        CANDIDATE_NOT_FOUND,
        CANDIDATE_ALREADY_EXISTS,
        COMPLAIN_ALREADY_EXISTS,
        COMPLAIN_NOT_FOUND,
        FEEDBACK_CREATION_FAILED,
        FEEDBACK_NOT_FOUND,
        FEEDBACK_DELETION_FAILED,
        FEEDBACK_UPDATE_FAILED,
        REPLIED_COMPLAINT_CREATION_FAILED,
        REPLIED_COMPLAINT_NOT_FOUND,
        REPLIED_COMPLAINT_DELETION_FAILED,
        REPLIED_COMPLAINT_UPDATE_FAILED,
        RESULT_CREATION_FAILED,
        RESULT_NOT_FOUND,
        RESULT_DELETION_FAILED,
        RESULT_UPDATE_FAILED,
        VOTE_DELETION_FAILED,
        VOTE_CREATION_FAILED,
        VOTE_NOT_FOUND,
        VOTE_ALREADY_COMPLETED,
        VOTE_UPDATE_FAILED




    }
}

